export const englishWishes = [
  "Wishing you a Diwali filled with joy, prosperity, and happiness. May your life be illuminated with the lights of joy!",
  "May the festival of lights fill your life with joy, happiness, and prosperity. Happy Diwali!",
  "Wishing you and your family a joyous Diwali filled with love, laughter, and endless blessings.",
  "May the spirit of Diwali bring you peace and happiness. Have a wonderful celebration!",
  "Wishing you a Diwali that brings happiness, prosperity, and joy to your life. Happy Diwali!",
  "May the lights of Diwali guide you on the path of success and happiness. Have a wonderful celebration!",
  "Wishing you a Diwali as bright as your spirit and as colorful as your dreams. Happy Diwali!",
  "May this Diwali bring new happiness, new goals, and new achievements. Have a great celebration!",
  "On this auspicious occasion of Diwali, may you be blessed with health, wealth, and prosperity.",
  "Wishing you a Diwali filled with sweet memories, beautiful moments, and wonderful celebrations.",
  "May the glow of the Diyas light your path to success and happiness. Happy Diwali!",
  "Wishing you peace, prosperity, and success on this Diwali. May your dreams come true!",
  "May the festival of lights brighten your life with joy and happiness. Happy Diwali!",
  "Wishing you a Diwali full of sweets, lights, and joy. Have a fantastic celebration!",
  "May your home be filled with the joy of Diwali and your life with the blessings of happiness.",
  "Wishing you a Diwali that’s as sweet as the treats and as bright as the fireworks!",
  "On this Diwali, may you be surrounded by love, laughter, and joy. Have a blessed celebration!",
  "May the beauty of Diwali fill your home with happiness and your life with joy.",
  "Wishing you a Diwali filled with fun and frolic. Enjoy the festival with your loved ones!",
  "May the warmth of Diwali bring you comfort and joy in the coming year.",
  "Wishing you and your loved ones a prosperous and joyful Diwali!",
  "On this auspicious occasion, may your life be filled with happiness and joy. Happy Diwali!",
  "May the lights of Diwali illuminate your path and guide you to success.",
  "Wishing you a joyful Diwali filled with moments of love, laughter, and joy.",
  "May this Diwali bring you new opportunities and success in all your endeavors.",
  "Wishing you a Diwali that sparkles with joy and brings happiness to your life.",
  "On this festive occasion, may you be blessed with wealth and prosperity. Happy Diwali!",
  "Wishing you peace, happiness, and joy on this Diwali. Have a wonderful celebration!",
  "May the festival of lights bring you joy, happiness, and prosperity. Happy Diwali!",
  "Wishing you a Diwali filled with bright lights and warm memories.",
  "On this Diwali, may you be surrounded by love and happiness. Enjoy the festivities!",
  "May this Diwali light up your life and fill it with joy and prosperity. Happy Diwali!",
];
